import {useEffect, useState, useRef} from 'react';
import Head from '../node_modules/next/head';
import { Contract, providers } from 'ethers';
import { formatEther } from '../node_modules/ethers/lib/utils';
import Web3Modal from 'web3modal';
import { KhaNFTContractAddress,
         KHANFTCONTRACTABI,
         DAO_CONTRACT_ADDRESS,
         DAO_CONTRACT_ABI
        } from '../Constants/constants';

const DAO = () => {



  return (
    <main className="h-screen bg-cover bg-[url('/img/ethereum.jpeg')]">
      <Head>
        <title>LW3 Sophomore Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;1,400&display=swap');
        </style>
      </Head>


      </main>
  )
}

export default DAO