import {useState, useEffect, useRef} from 'react';
import Head from '../node_modules/next/head';
import { BigNumber, Contract, providers, utils } from '../node_modules/ethers/lib/ethers';
import Web3Modal from 'web3modal';
import { 
     KhaNFTContractAddress,
     KHANFTCONTRACTABI,
     KHANFT_TOKEN_ADDRESS,
     KHANFT_TOKEN_CONTRACT_ABI
 } from '../Constants/constants';


const ICO = () => {



  return (
    <main className="h-screen bg-cover bg-[url('/img/ethereum.jpeg')]" >
        <Head>
        <title>LW3 Sophomore Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;1,400&display=swap');
        </style>
      </Head>
      <div className='flex flex-col items-center h-96 justify-center'>
        <h1 className='text-5xl text-center py-4 text-white'>
            Initial Coin Offering
        </h1>
        {/* {renderButton()} */}

    </div>
    </main>
  )
}

export default ICO