import React from "react";
import Head from "../node_modules/next/head";

const Home = () => {
  return <main className="h-screen bg-cover bg-[url('/img/ethereum.jpeg')]" >
    <Head>
        <title>Patient Records</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;1,400&display=swap');
        </style>
      </Head>
    <div className="p-6 text-white flex flex-col justify-center h-5/6 ">
        <h1 className="text-4xl">LearnWeb3 Sophomore Dapps</h1>
        <ul className="p-4 text-2xl">
          <li className="list-disc cursor-pointer border-b-2 border-blue-500 w-44">Whitelist Dapp</li>
          <li className="list-disc cursor-pointer border-b-2 border-blue-500 w-44">NFT Collection</li>
          <li className="list-disc cursor-pointer border-b-2 border-blue-500 w-44">ICO</li>
          <li className="list-disc cursor-pointer border-b-2 border-blue-500 w-44">DAO</li>
          <li className="list-disc cursor-pointer border-b-2 border-blue-500 w-44">DeFi-Exchange</li>
        </ul>
    </div>
  </main>
}

export default Home