import {useState, useEffect, useRef} from 'react';
import Head from '../node_modules/next/head';
import Web3Modal from 'web3modal';
import { providers, Contract } from '../node_modules/ethers/lib/ethers';
import { KhaNFTContractAddress, KHANFTCONTRACTABI } from '../Constants/constants';
import { toast } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";

const KhaNFT = () => {







  return (
    <main className="h-screen bg-cover bg-[url('/img/ethereum.jpeg')]" >
        <Head>
        <title>LW3 Sophomore Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;1,400&display=swap');
        </style>
      </Head>
      <div className='flex flex-col items-center h-96 justify-center'>
        <h1 className='text-5xl text-center py-4 text-white'>
            Welcome to KhaNFT
        </h1>
        <p
        className='text-2xl'
        >It's an NFT collection for Khans(giga Chads)</p>
        {/* {renderButton()} */}
        <button
                className='border-2 transition duration-300 ease-out hover:ease-in hover:bg-purple-800 text-3xl rounded px-3 py-2 hover:text-white my-4'
                >
                Connect Wallet
                </button>
        <p className='text-2xl'>2/20 NFTs have been minted</p>
    </div>
    </main>
  )
}

export default KhaNFT