import React from 'react'
import Head from '../node_modules/next/head'

const Whitelist = () => {
  return (
    <main className="h-screen bg-cover bg-[url('/img/ethereum.jpeg')]" >
        <Head>
        <title>LW3 Sophomore Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;1,400&display=swap');
        </style>
      </Head>
      <div className='flex flex-col items-center h-96 justify-center'>
        <h1 className='text-5xl text-center py-4 text-white'>
            Whitelist Dapp
        </h1>
        <button
        className='border-2 transition duration-300 motion-safe:animate-bounce ease-out hover:ease-in hover:bg-purple-800 text-3xl rounded px-3 py-2 hover:text-white mb-3'
        >
        Join Whitelist
        </button>
        <p className='text-2xl'>Total Members Joined is 13</p>
    </div>
    </main>
  )
}

export default Whitelist